spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
        access-key: LTAI5t8G7x98cxA7UhvmfPnj
        secret-key: AJ6aZUrCXO5G8VItAeSUZmmXVE1L4g
        oss:
          endpoint: oss-cn-beijing.aliyuncs.com
          bucket: mall-kkzz
  application:
    name: mall-third-party

server:
  port: 30000
